### ISSUE TITLE
Multiple playback errors when direct playing or transcoding

### ISSUE THREAD

**Issue by cmgfender** [DEFENDORe/pseudotv#37] opened 2020-05-22 16:00 UTC
Hello!

I was using the latest (stable) build of PseudoTV, and kept getting these errors.
<img width="960" alt="Screen Shot 2020-05-22 at 11 11 38 AM" src="https://user-images.githubusercontent.com/2956801/82686281-97a23580-9c23-11ea-9775-5f0ace8f5182.png">
<img width="1792" alt="Screen Shot 2020-05-22 at 11 13 43 AM" src="https://user-images.githubusercontent.com/2956801/82686282-983acc00-9c23-11ea-973d-c334555ef43d.png">
<img width="1792" alt="Screen Shot 2020-05-22 at 11 13 54 AM" src="https://user-images.githubusercontent.com/2956801/82686286-9a048f80-9c23-11ea-8ab6-e3cf26583b3c.png">

Then I updated to the direct play build, turned it all to direct play, and would get an instant crash. I then added "?" to the end of the VIDEOSTREAM and AUDIOSTREAM arguments, and would still get the instant crash.

I went back to transcoding, and its "working" but buffering way more often than it ever did before.

**Comment by powdermilkman** [comment] 2020-05-25 08:20
Duplicate of #26

**Closed by powdermilkman** 2020-05-25 08:20 UTC
